version: '3'

silent: true

tasks:
  default:
    cmds:
      - task -l

  build:
    cmds:
      - go build -v -i main.go

  start:
    desc: "Start uvicorn server"
    cmds:
      - poetry run uvicorn whats-my-acb.main:app --reload
